name: polis-analysis
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - numpy=1.26.0
  - scikit-learn=1.3.0
  - pandas
  - umap-learn #from: conda-forge
  - importlib-metadata #from: anaconda
  - seaborn
  - matplotlib
  - altair
  - jupyter
  - pip
  - pip:
    - numba==0.57.0

